export function helpText(): string[] {
  return [
    '',
    'Usage: tower <command>',
    '',
    'Commands:',
    '  create           Scaffold a new Tower application',
    '  create --name my-app --modules vault,gatehouse  Scaffold non-interactively',
    '  create --js my-app          Scaffold a plain JavaScript app (default is TypeScript)',
    '  about            Show application, module, runtime, and environment diagnostics',
    '  migrate          Run database and auth migrations',
    '  migrate --seed   Run migrations, then seeds',
    '  seed             Run seeds (runs migrations first unless --skip-migrate)',
    '  seed --skip-migrate  Run seeds without running migrations first',
    '  db migrate        Run pending database and auth migrations',
    '  db rollback       Roll back the most recent migration',
    '  db status         Show executed vs pending migrations',
    '  db refresh        Roll back all migrations, then re-run them',
    '  db fresh          Drop the schema, then migrate from scratch',
    '  db seed           Run database seeds',
    '  db setup          Migrate, auth migrations, then seed — first-run helper',
    '  make model|migration|policy|factory|job <Name>  Generate starter files',
    '  config show      Print the resolved configuration (secrets redacted)',
    '  dev              Validate and start the Next.js dev server on port 3000',
    '  help             Show this message',
    '  --version, -v    Show version',
    '',
  ]
}
