services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tower
      POSTGRES_USER: tower
      POSTGRES_PASSWORD: tower
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
